apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: playground-namespace-cleaner
  namespace: kube-system
  labels:
    branch: _BRANCH_SLUG_
spec:
  schedule: "* * * * *" # every minute
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: ns-cleaner
            image: eu.gcr.io/um-website-193311/kube-system/ns-cleaner:_BRANCH_SLUG_
            imagePullPolicy: Always
            args:
              - /bin/sh
              - -c
              - /usr/bin/ns-cleaner
          restartPolicy: Never
